version: '3.7'

services:
  web:
      build: .
      ports:
          - '8080:8080'
      user: "node"
      volumes:
          - database:/home/node/database:rw
      env_file: ".env"
      restart: always
volumes:
    database: