version: '3.7'

services:
  api:
      build: shopper-node-technical-test
      ports:
          - '3000:3000'
      user: "node"
      volumes:
          - database:/home/node/database:rw
      env_file: ".env"
      restart: always
  web:
    build: shopper-front-end-technical-test
    ports: 
      - '80:8080'
    user: 'node'
    restart: always
volumes:
    database: